[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
