# Netlify Configuration File
# This file tells Netlify how to build and deploy your site.

[build]
  # This is the directory that contains your deployed website files.
  # Since your index.html is in the root, we set this to the current directory.
  publish = "."
  
  # This is the directory where Netlify will find your serverless functions.
  functions = "netlify/functions"

# This rule is helpful for single-page applications. It ensures that any
# direct navigation to a path on your site still loads the main index.html.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
